all: book1 book2 book3

book1:book1.cpp
	g++ -g -o book1 book1.cpp -lpthread 

book2:book2.cpp
	g++ -g -o book2 book2.cpp -lpthread 

book3:book3.cpp
	g++ -g -o book3 book3.cpp -lpthread 

clean:
	rm book1 book2 book3
