all: book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12

book1:book1.cpp
	g++ -g -o book1 book1.cpp -lpthread

book2:book2.cpp
	g++ -g -o book2 book2.cpp -lpthread

book3:book3.cpp
	g++ -g -o book3 book3.cpp -lpthread

book4:book4.cpp
	g++ -g -o book4 book4.cpp -lpthread

book5:book5.cpp
	g++ -g -o book5 book5.cpp -lpthread

book6:book6.cpp
	g++ -g -o book6 book6.cpp -lpthread

book7:book7.cpp
	g++ -g -o book7 book7.cpp -lpthread

book8:book8.cpp
	g++ -g -o book8 book8.cpp -lpthread

book9:book9.cpp
	g++ -g -o book9 book9.cpp -lpthread

book10:book10.cpp
	g++ -g -o book10 book10.cpp -lpthread

book11:book11.cpp
	g++ -g -o book11 book11.cpp -lpthread

book12:book12.cpp
	g++ -g -o book12 book12.cpp -lpthread -std=c++11


clean:
	rm book1 book2 book3 book4 book5 book6 book7 book8 book9 book10 book11 book12
