all: book1 book2 book3 book4 book5

book1:book1.cpp
	g++ -g -o book1 book1.cpp -lpthread

book2:book2.cpp
	g++ -g -o book2 book2.cpp -lpthread

book3:book3.cpp
	g++ -g -o book3 book3.cpp -lpthread

book4:book4.cpp
	g++ -g -o book4 book4.cpp -lpthread

book5:book5.cpp
	g++ -g -o book5 book5.cpp -lpthread

clean:
	rm book1 book2 book3 book4 book5
